project:
  type: website
  output-dir: docs

website:
  title: "Beyzanur Nas's Analytics Lab" 
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd
      - text: My Posts
        menu: 
          - text: POSTS
            href: posts.qmd
          - text: Forest Allocation
            href: allocation.qmd
          - text: Task Scheduling
            href: scheduling.qmd
          - text: Set Covering
            href: msc.qmd
          - text: Traveling Salesman Problem
            href: tsp.qmd            
          - text: Vehicle Routing Problem
            href: vrp.qmd
          - text: Oil Blending
            href: blending.qmd
          - text: Linear Separator
            href: linsep.qmd
      - text: "EMU430 Coursework"
        menu:
          - text: Assignments
            href: assignments.qmd
          - text: Project
            href: project.qmd
            
    tools:
      - icon: github
        href: https://github.com/beyzanurnas
      - icon: linkedin
        href: https://tr.linkedin.com/in/beyzanurnas


  sidebar:
    - title: "Assign..."
      style: "docked"
      search: true
      contents:
        #- assignments.qmd
        #- assignments/assignment-1.qmd
        #- assignments/assignment-2.qmd  
        - posts.qmd
        - allocation.qmd
        - scheduling.qmd
        - msc.qmd
        - tsp.qmd
        - vrp.qmd
        - blending.qmd
        - linsep.qmd
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU 430 - Fall 2023" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: 
      light: sandstone 
      dark: slate
    css: styles.css


editor: visual

